version: '2'
services:
    jhipsteroauth2sampleapplication-app:
        image: jhipsteroauth2sampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipsteroauth2sampleapplication-mariadb:3306/jhipsteroauth2sampleapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsteroauth2sampleapplication-mariadb:
        extends:
            file: mariadb.yml
            service: jhipsteroauth2sampleapplication-mariadb
